# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      redis:
        # Docker Hub image
        image: redis:alpine
        ports:
          - 6379:6379
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_PASSWORD: example
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
        #volumes:
        #  - ${{ github.workspace }}/prospector/ddl:/docker-entrypoint-initdb.d
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - name: Set up Postgres tables
        run: |
          psql -h localhost -U postgres -d postgres -f prospector/ddl/10_commit.sql
          psql -h localhost -U postgres -d postgres -f prospector/ddl/20_users.sql
        env:
          PGPASSWORD: example
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.6
      - name: Setup python environment
        run: |
          python -m pip install --upgrade pip
          cd prospector
          cp config-sample.yaml config.yaml
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          python -m spacy download en_core_web_sm
      - name: Flake8
        uses: TrueBrain/actions-flake8@master
        with:
          path: prospector
          max_line_length: 100
          ignore: E203,E501,W503,F401,F403,E999
      - name: Test with pytest
        env:
          GIT_CACHE: "/tmp/git-cache"
          POSTGRES_USER: "postgres"
          POSTGRES_PASSWORD: "postgres"
          POSTGRES_HOST: "localhost"
          POSTGRES_PORT: "5432"
          POSTGRES_DBNAME: "postgres"
          REDIS_URL: ""
        run: |
          cd prospector
          [ -d /tmp/git-cache ] || mkdir -p /tmp/git-cache
          pytest
